USE bus_service_analysis;

------------------------------------creating staging table------------------------------------
CREATE TABLE bus_daily_stages(
	[DATE] VARCHAR(20),
	UJJAIN_DEP VARCHAR(20),
	UNHEL_DEP VARCHAR(20),
	NAGDA_DEP VARCHAR(20),
	KHACHROD_DEP VARCHAR(20),
	JAORA VARCHAR(20),
	KHACHROD VARCHAR(20),
	NAGDA VARCHAR(20),
	UNHEL VARCHAR(20),
	BADNAGAR VARCHAR(20),
	LUGGAGE VARCHAR(20),
	DIESEL VARCHAR(20),
	MAINTENANCE VARCHAR(20),
	LABOUR VARCHAR(20),
	COLLECTED VARCHAR(20),
	OTHER_EXPENSES VARCHAR(20),
	PASSENGER_REVENUE VARCHAR(20),
	GROSS_INCOME VARCHAR(20),
	TOTAL_EXPENSES VARCHAR(20),
	NET_INCOME VARCHAR(20),
	DRIVER VARCHAR(100),
	CONDUCTOR VARCHAR(100),
	DISCREPANCY VARCHAR(100),
	NOTE VARCHAR(255)
);

SELECT *
FROM bus_daily_stages;



----------------------------------------------bulk inserting data in bus staging table from source----------------------
BULK INSERT bus_daily_stages
FROM 'C:\Users\asus\Downloads\Income_sheeet_MP13P1993.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    TABLOCK
);

-----------------------------------------------creating table to store the records------------------------------
CREATE TABLE bus_daily_records(
	[DATE] DATE,
	UJJAIN_DEP DECIMAL(10,2),
	UNHEL_DEP DECIMAL(10,2),
	NAGDA_DEP DECIMAL(10,2),
	KHACHROD_DEP DECIMAL(10,2),
	JAORA DECIMAL(10,2),
	KHACHROD DECIMAL(10,2),
	NAGDA DECIMAL(10,2),
	UNHEL DECIMAL(10,2),
	BADNAGAR DECIMAL(10,2),
	LUGGAGE DECIMAL(10,2),
	DIESEL DECIMAL(10,2),
	MAINTENANCE DECIMAL(10,2),
	LABOUR DECIMAL(10,2),
	COLLECTED DECIMAL(10,2),
	OTHER_EXPENSES DECIMAL(10,2),
	PASSENGER_REVENUE DECIMAL(10,2),
	GROSS_INCOME DECIMAL(10,2),
	TOTAL_EXPENSES DECIMAL(10,2),
	NET_INCOME DECIMAL(10,2),
	DRIVER VARCHAR(100),
	CONDUCTOR VARCHAR(100),
	DISCREPANCY VARCHAR(100),
	NOTE VARCHAR(255)
);

------------------------------------------------Inserting data with corrected data types------------------------------
INSERT INTO bus_daily_records
SELECT
	COALESCE(
		TRY_CONVERT(DATE, [DATE], 103),
		TRY_CONVERT(DATE, [DATE],5)
	) AS [DATE],
    TRY_CONVERT(DECIMAL(10,2), NULLIF(UJJAIN_DEP, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(UNHEL_DEP, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(NAGDA_DEP, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(KHACHROD_DEP, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(JAORA, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(KHACHROD, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(NAGDA, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(UNHEL, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(BADNAGAR, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LUGGAGE, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(DIESEL, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(MAINTENANCE, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(LABOUR, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(COLLECTED, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(OTHER_EXPENSES, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(PASSENGER_REVENUE, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(GROSS_INCOME, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(TOTAL_EXPENSES, '')),
    TRY_CONVERT(DECIMAL(10,2), NULLIF(NET_INCOME, '')),
    DRIVER,
    CONDUCTOR,
    NULLIF(DISCREPANCY, ''),
    NOTE
FROM bus_daily_stages;

---------------------------------Applying checks to ensure data inserted properly--------------------
SELECT *
FROM bus_daily_records
WHERE [DATE] IS NULL;

SELECT TOP 10 *
FROM bus_daily_records 
WHERE GROSS_INCOME IS NULL OR TOTAL_EXPENSES IS NULL OR NET_INCOME IS NULL;

